name: "Code Quality"
on: pull_request
permissions: write-all
jobs:
  code-quality-ticket-ref:
    name: "Ticket Reference"
    runs-on: ubuntu-latest
    steps:
      - id: jira
        continue-on-error: true
        uses: FidelusAleksander/gh-action-regex@master
        with:
          regex_pattern: "[A-Z|a-z]+-[0-9]+"
          text: ${{ github.event.pull_request.title }}

      - uses: marocchino/sticky-pull-request-comment@v2.6.2
        if: steps.jira.outputs.match == 'false' && github.event_name == 'pull_request' && (success() || failure())
        with:
          hide_and_recreate: true
          header: "JIRA_REC"
          message: |
            WARNING: Missing Jira Ticket Reference
              
            Pull Requests should reference a Jira ticket in their title. 

            If a PR address multiple tickets, the title should include the primary ticked and include the remaining ticket references in the PR description.

      - uses: actions/github-script@v3
        if: steps.jira.outputs.match == 'false' && (success() || failure())
        with:
          script: |
            core.warning('WARNING: Pull Requests does not reference a Jira ticket in it's title. ')
  code-quality-unit-tests:
    name: "Unit Tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - run: dotnet test "Test Solution.sln" --results-directory "TestResults/" --settings .runsettings
