name: "CheckCoverage"
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: ["main"]
permissions: write-all
jobs:
  CheckCoverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - run: dotnet test "Test Solution.sln" --results-directory "TestResults/" --settings .runsettings
      - run: dotnet tool restore
        if: always()

      - name: Merge code coverage results
        run: dotnet tool run dotnet-coverage merge TestResults/ --recursive --output TestResults/coverage-cobertura.xml --output-format cobertura --remove-input-files
        if: always()

      - uses: mlafleur/code-coverage-report-action@v01.2.0-alpha
        name: Coverage by Package
        id: code_coverage_report_action
        if: always()
        with:
          filename: "TestResults/coverage-cobertura.xml"
          fail_on_negative_difference: true
          markdown_filename: code-coverage-diff
          artifact_download_workflow_names: "CheckCoverage"

      - name: Publish package coverage validation results
        uses: marocchino/sticky-pull-request-comment@v2.6.2
        if: steps.code_coverage_report_action.outputs.file != '' && github.event_name == 'pull_request' && (success() || failure())
        with:
          recreate: true
          path: code-coverage-diff.md

      - uses: mlafleur/code-coverage-report-action@v01.2.0-alpha
        name: Overall Coverage
        id: overall_code_coverage_report_action
        if: always()
        with:
          filename: "TestResults/coverage-cobertura.xml"
          fail_on_negative_overall_difference: true
          markdown_filename: overall-code-coverage-diff
          report_overall_coverage: true
          report_package_coverage: false
          artifact_download_workflow_names: "CheckCoverage"

      - name: Publish overall coverage validation results
        uses: marocchino/sticky-pull-request-comment@v2.6.2
        if: steps.code_coverage_report_action.outputs.file != '' && github.event_name == 'pull_request' && (success() || failure())
        with:
          recreate: true
          path: overall-code-coverage-diff.md
