# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    # branches: [ "main" ]
  pull_request:
    # branches: [ "main" ]

jobs:
  CheckCoverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - run: dotnet test "Test Solution.sln" --results-directory "TestResults/" --settings .runsettings
      - run: dotnet tool restore
      - run: dotnet tool run dotnet-coverage merge TestResults/ --recursive --output coverage-final.xml --output-format cobertura 
      - name: Archive coverage report (xml)
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage-final.xml

